### ISSUE TITLE
when can ih how hw when can i develop on the client ice bear client cheat for minecaaft based on MCP

### ISSUE THREAD

**Issue by Spinyfish** [Syntex1337/IceBearClient#1]
yes thank you hello i am spinyfhh (C++ developer for 3+ years and java for 4+) i would like to work on the famous minecraft hack application ice bear because i think that i am the would be a value am an asset to yout team, i require 24$ an hour or paid per task thank you gooday.

**Comment by Syntex1337** [comment]
hi, we dont trust spinyfish , he skids, and never gave me mint client's src

**Comment by Spinyfish** [comment]
sir you seem to be misinformed, mint is open source, check it out at https://github.com/Spinyfish/MintClient

**Comment by Syntex1337** [comment]
i suppose it isnt open source sir,
![Screenshot 2023-02-16 215327](https://user-images.githubusercontent.com/123810169/219383426-d85fed3b-c638-4fd7-a7cd-2d8b32a0a527.png)
if possbile if u shared ur repo i would be happy thanks

**Comment by Spinyfish** [comment]
Sir? It works for me, perhaps you are having a wifi issue.

**Comment by Syntex1337** [comment]
now it works thanks sir

**Comment by Syntex1337** [comment]
never
